---
- name: Apt, cleanup existing repos files
  when:
    - repos_cleanup_existing | bool
  block:
    - name: Apt, cleanup sources.list
      become: true
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent

    - name: Apt, create empty sources.list
      become: true
      ansible.builtin.copy:
        dest: "/etc/apt/sources.list"
        content: |
          # Ansible managed
        owner: root
        group: root
        mode: "0644"

    - name: Apt, identify sources.list.d/* for cleanup
      become: true
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d
        patterns: "*"
      register: old_repos_files_to_delete

    - name: Apt, cleanup sources.list.d/*
      become: true
      loop: "{{ old_repos_files_to_delete.files | flatten }}"
      loop_control:
        loop_var: file
        label: "file: {{ file.path }}"
      ansible.builtin.file:
        path: "{{ file.path }}"
        state: absent
  

- name: Apt, manage repos
  when: >
    (
      repos_list is defined
      and
      repos_list[ansible_distribution | lower][ansible_distribution_release | lower] is iterable
    )
    or
    (
      repos_list_host is defined
      and
      repos_list_host[ansible_distribution | lower][ansible_distribution_release | lower] is iterable
    )
    or
    (
      repos_list_group is defined
      and
      repos_list_group[ansible_distribution | lower][ansible_distribution_release | lower] is iterable
    )
  block:
    - name: Apt, manage repos
      loop: >-
        {{ repos_list[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_list_host[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_list_group[ansible_distribution | lower][ansible_distribution_release | lower] | default([])
        | flatten(levels=1) }}
      loop_control:
        loop_var: repo
        label: "repo: {{ repo.name }}"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/action_apt_repository.yml

    - name: Apt, manage keys
      loop: >-
        {{ repos_list[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_list_host[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_list_group[ansible_distribution | lower][ansible_distribution_release | lower] | default([])
        | flatten(levels=1) }}
      loop_control:
        loop_var: repo
        label: "repo: {{ repo.name }}"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/action_apt_key.yml


- name: Apt, manage repos dl pkgs
  when: >
    (
      repos_dl_pkgs_list is defined
      and
      repos_dl_pkgs_list[ansible_distribution | lower][ansible_distribution_release | lower] is iterable
    )
    or
    (
      repos_dl_pkgs_list_host is defined
      and
      repos_dl_pkgs_list_host[ansible_distribution | lower][ansible_distribution_release | lower] is iterable
    )
    or
    (
      repos_dl_pkgs_list_group is defined
      and
      repos_dl_pkgs_list_group[ansible_distribution | lower][ansible_distribution_release | lower] is iterable
    )
  block:
    - name: Apt, remove repos dl pkgs
      become: true
      when: repos_dl_pkgs_list[ansible_distribution | lower][ansible_distribution_release | lower] | default(false)
      loop: >-
        {{ repos_dl_pkgs_list[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_dl_pkgs_list_host[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_dl_pkgs_list_group[ansible_distribution | lower][ansible_distribution_release | lower] | default([])
        | flatten(levels=1) }}
      loop_control:
        loop_var: repo
        label: "repo: {{ repo.name }}"
      ansible.builtin.apt:
        name: "{{ repo.name }}"
        state: absent

    - name: Apt, install repos dl pkgs
      become: true
      when: repos_dl_pkgs_list[ansible_distribution | lower][ansible_distribution_release | lower] | default(false)
      loop: >-
        {{ repos_dl_pkgs_list[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_dl_pkgs_list_host[ansible_distribution | lower][ansible_distribution_release | lower] | default([]) +
        repos_dl_pkgs_list_group[ansible_distribution | lower][ansible_distribution_release | lower] | default([])
        | flatten(levels=1) }}
      loop_control:
        loop_var: repo
        label: "repo: {{ repo.name }}"
      ansible.builtin.apt:
        deb: "{{ repo.url }}"
        state: present
